name: Deploy Website

on:
  push:
    branches:
      - main

# Добавили переменную, чтобы убрать желтое предупреждение Node.js 20
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Deploy files via rsync
      uses: easingthemes/ssh-deploy@v4
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: "5.181.253.175"
        REMOTE_USER: "root"
        TARGET: "/var/www/pguopoprating/"
        SOURCE: "./"
        EXCLUDE: "/venv/, /.git/, /.github/"

    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: "5.181.253.175"
        username: "root"
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          /var/www/pguopoprating/venv/bin/pip install -r /var/www/pguopoprating/requirements.txt
          systemctl restart pguopoprating
          systemctl enable pguopoprating